name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      composer_require_extra: silverstripe/recipe-cms:^5
      dynamic_matrix: false
      extra_jobs: |
        - php: 8.1
          phplinting: true
          phpunit: true
